structure=PO3_6326969.mol

consumptionratio=1
jobsatsametime=2
coresperjob=48

atmidx=550
new_gdma=True
gdmacommand_Radius_S=0.80
prmmodfile=dma4_hfe2023_1

dontfrag=True

rotalltors=True
refinenonaroringtors=True
nonaroringtor1Dscan=True

#rotalltors=False
#refinenonaroringtors=False
#nonaroringtor1Dscan=False

